### ISSUE TITLE
去除Promise化后  代码该怎么改？

### ISSUE THREAD

**Issue by lxljl** [simmzl/mini-program-of-CQS#2]
不要这两句该如何改？
this.use('requestfix'); 修复小程序请求并发问题
this.use('promisify'); 原生API都将Promise化
假如加了以上两句代码  ， 以前的代码 会变成不可用，  所以问问 ？

**Comment by simmzl** [comment]
不使用promise就用官方的回调函数，api里传入对应回调就行了 @lxljl
