### ISSUE TITLE
基本不好使

### ISSUE THREAD

**Issue by endfish** [simmzl/mini-program-of-CQS#5]
先是报错:
"Support for the experimental syntax 'classProperties' isn't currently enabled (19:11):"

安装"plugin-proposal-class-properties"插件后又报错"Can't resolve 'wepy'"
解决后又出警告
Missing wepy entry. A .wpy file should have "wepy.app", "wepy.page" or "wepy.component"

....

**Comment by simmzl** [comment]
时间太久了😂，重新疏通了下，你可以pull最新试试。
⚠️注意wepy用1.x，仓库里用的1.7.0
